project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "EST328 - Análise Multivariada e Aprendizado Não Supervisionado"
  description: "Homepage da disciplina EST328 - Análise Multivariada e Aprendizado Não Supervisionado, 2026/2"
  site-url: "http://professortp.com.br/est328/"

  repo-url: "https://github.com/tiagomartin/est328"
  repo-actions: [edit, issue]

  open-graph: true
  
  page-footer:
    right: "Página construída usando [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2026, Tiago Pereira"


  sidebar:
    tools: 
    - icon: github
      text: github
      href: https://github.com/tiagomartin/est328
    background: "#F2F2F2"
    logo: "images/logo.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - aulas.qmd
      #- estudos.qmd
      - exercicios.qmd
      - analises.qmd
      - plano.qmd
      #- projeto.qmd
      - cronograma.qmd
      #- material.qmd

      
format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: false

