---
title: "Cronograma da Disciplina"
tbl-colwidths: [5,10,30,5,5,5,5,5,5,5]
---

Esta página contém um esboço dos tópicos, conteúdos e tarefas para o semestre. Este cronograma será atualizado conforme o semestre avança.

<!-- https://fontawesome.com/search?o=r&m=free -->

<!-- https://jpswalsh.github.io/academicons/ -->

<!-- [{{< fa file-pdf size=2xl >}}](/weeks/week-1.html#prepare){aria-label="Week 1 summary"}  |  [️](/slides/lec-1.html "Lecture slides"){aria-label="Lecture 1 slides"}  |       [{{< fa laptop-file size=2xl >}}](/ae/ae-0-movies.html "Application exercise"){aria-label="Application Exercise 0 instructions"} -->

<!-- {{< fa brands r-project size=2xl >}}  -  scripts -->

<!-- {{< fa file-powerpoint size=2xl >}}   -  slides -->

<!-- {{< fa laptop-file size=2xl >}}  -  estudo de caso -->

<!-- {{< fa file-pdf size=2xl >}}  -  artigo -->

<!-- {{< fa table size=2xl >}}  -  tabelas estatisticas -->

<!-- {{< fa file-lines size=2xl >}}  -  exercicios -->

<!-- {{< fa folder size=2xl >}}  -  material complementar -->

<!-- {{< fa list-check size=2xl >}}  -  projeto -->

::: column-screen-inset-right
| Semana | Data | Tópico | Artigo | Slides | EC | LE | Script | MC | Projeto |
|:------:|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| [1](programacao/semana-1.html) | Seg, 24/08 | Apresentação da disciplina |  |  |  |  |  |  |  |
|  | Qua, 26/08 | Revisão de Álgebra Linear |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/revisao_alg_linear/rev_alg_linear.html#/title-slide "Revisão de Álgebra Linear"){aria-label="Revisão de Álgebra Linear"} |  |  |  |  |  |
| [2](programacao/semana-2.html) | Seg, 31/08 | Revisão de Álgebra Linear |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/revisao_alg_linear/rev_alg_linear.html#/title-slide "Revisão de Álgebra Linear"){aria-label="Revisão de Álgebra Linear"} |  |  |  |  |  |
|  | Qua, 02/09 | Introdução à Estatística Multivariada |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/intro_est_multi/intro_est_multi.html#/title-slide "Introdução à Estatística Multivariada"){aria-label="Introdução à Estatística Multivariada"} |  | [{{< fa file-lines size=2xl >}}](/exercicios/lista01.html "Lista de Exercícios 01"){aria-label="Lista de Exercícios 01"} |  |  |  |
| [3](programacao/semana-3.html) | Se, 07/09 | **Feriado: Independência do Brasil** |  |  |  |  |  |
|  | Qui, 09/09 | Introdução à Estatística Multivariada |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/intro_est_multi/intro_est_multi.html#/propriedades-da-média-e-da-variância-de-vetores-aleatórios "Introdução à Estatística Multivariada"){aria-label="Introdução à Estatística Multivariada"} |  |  |  |  |  |
<!-- | [4](programacao/semana-4.html) | Ter, 28/10 | Introdução à Estatística Multivariada |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/intro_est_multi/intro_est_multi.html#/distância-euclidiana-1 "Introdução à Estatística Multivariada"){aria-label="Introdução à Estatística Multivariada"} |  |[{{< fa file-lines size=2xl >}}](/exercicios/lista02.html "Lista de Exercícios 02"){aria-label="Lista de Exercícios 02"}  | [{{< fa brands r-project size=2xl >}}](/analise_dados/descr_vis_iris.html "Análise de dados"){aria-label="Análise de dados"} |  |  | -->
<!-- |  | Qui, 30/10 | **Não haverá aula: Paralização docente** |  |  |  |  |  |  |  | -->
<!-- | [5](programacao/semana-5.html) | Ter, 04/11 | Distribuição Normal Multivariada |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/distr_normal_multi/distr_normal_multi.html "Distribuição Normal Multivariada"){aria-label="Distribuição Normal Multivariada"} |  |  |  |  |  | -->
<!-- |  | Qui, 06/11 | Distribuição Normal Multivariada |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/distr_normal_multi/distr_normal_multi.html#/distribuição-normal-multivariada-6 "Distribuição Normal Multivariada"){aria-label="Distribuição Normal Multivariada"} |  |  |  |  |  | -->
<!-- | [6](programacao/semana-6.html) | Ter, 11/11 | Análise de Componentes Principais |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/analise_comp_princ/comp_princ.html#/title-slide "Análise de Componentes Principais"){aria-label="Análise de Componentes Principais"} |  |[{{< fa file-lines size=2xl >}}](/exercicios/lista03.html "Lista de Exercícios 03"){aria-label="Lista de Exercícios 03"}  |  |  |  | -->
<!-- |  | Qui, 13/11 | Análise de Componentes Principais |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/analise_comp_princ/comp_princ.html#/title-slide "Análise de Componentes Principais"){aria-label="Análise de Componentes Principais"} |  |  |  |  |  | -->
<!-- | [7](programacao/semana-7.html) | Ter, 18/11 | Não haverá aula |  |  |  |  |  |  |  | -->
<!-- |  | Qui, 20/11 | Feriado: não haverá aula |  |  |  |  |  |  |  | -->
<!-- | [8](programacao/semana-8.html) | Ter, 25/11 | Análise de Componentes Principais |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/analise_comp_princ/comp_princ.html#/componentes-principais-variáveis-padronizadas "Análise de Componentes Principais"){aria-label="Análise de Componentes Principais"} |  | |  |  |  | -->
<!-- |  | Qui, 27/11 | Análise de Componentes Principais |  |  |  |  | [{{< fa brands r-project size=2xl >}}](/analise_dados/brands.html "Análise de dados"){aria-label="Análise de dados"} |  |  | -->
<!-- | [9](programacao/semana-9.html) | Ter, 02/12 | Análise Fatorial |  |[{{< fa file-powerpoint size=2xl >}}](/aulas/analise_fatorial/fatorial.html#/title-slide "Análise Fatorial"){aria-label="Análise Fatorial"}  |  |  |  |  |  [{{< fa list-check size=2xl >}}](/projeto/acp/acp.html "Projeto: Análise de Componentes Principais"){aria-label="Projeto: Análise de Componentes Principais"} -->
<!-- |  | Qui, 04/12 | Análise Fatorial |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/analise_fatorial/fatorial.html#/title-slide "Análise Fatorial"){aria-label="Análise Fatorial"} |  |  |  |  |  | -->
<!-- | [10](programacao/semana-10.html) | Ter, 09/12 | Não haverá aula! |  |  |  |  |  |  |  | -->
<!-- |  | Qui, 11/12 | Análise Fatorial |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/analise_fatorial/fatorial.html#/rotação-dos-fatores "Análise Fatorial"){aria-label="Análise Fatorial"} |  |  |  |  |  | -->
<!-- | [11](programacao/semana-11.html) | Ter, 16/12 | Análise Fatorial |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/analise_fatorial/fatorial.html#/contexto-empresa-telco "Análise Fatorial"){aria-label="Análise Fatorial"} |  |  |  |  |  | -->
<!-- |  | Qui, 18/12 | Não haverá aula |  |  |  |  |  |  |  | -->
<!-- |  |  | **22/12 a 17/01  -  Recesso Acadêmico** |  |  |  |  |  |  |  | -->
<!-- | [12](programacao/semana-12.html) | Ter, 20/01 | Análise de Agrupamentos |  |[{{< fa file-powerpoint size=2xl >}}](/aulas/analise_agrupamento/agrupamento.html#/title-slide "Análise de Agrupamentos"){aria-label="Análise de Agrupamentos"}  |  | |  [{{< fa brands r-project size=2xl >}}](/analise_dados/estudantes.html "Análise de dados"){aria-label="Análise de dados"}  |  |  [{{< fa list-check size=2xl >}}](/projeto/af/af.html "Projeto: Análise Fatorial"){aria-label="Projeto: Análise Fatorial"} -->
<!-- |  | Qui, 22/01 | Análise de Agrupamentos |  |[{{< fa file-powerpoint size=2xl >}}](/aulas/analise_agrupamento/agrupamento.html#/title-slide "Análise de Agrupamentos"){aria-label="Análise de Agrupamentos"}  |  |  |  |  |  | -->
<!-- | [13](programacao/semana-13.html) | Ter, 27/01 |  Análise de Agrupamentos |  |[{{< fa file-powerpoint size=2xl >}}](/aulas/analise_agrupamento/agrupamento.html#/métodos-de-agrupamento-hierárquicos-6 "Análise de Agrupamentos"){aria-label="Análise de Agrupamentos"}  |  |  |  |  |  | -->
<!-- |  | Qui, 29/01 |   Análise de Agrupamentos |  |[{{< fa file-powerpoint size=2xl >}}](/aulas/analise_agrupamento/agrupamento.html#/métodos-de-agrupamento-hierárquicos-6 "Análise de Agrupamentos"){aria-label="Análise de Agrupamentos"}  |  |  |  |  |  | -->
<!-- | [14](programacao/semana-14.html) | Ter, 03/02 | Análise de Agrupamentos |  |  |  | |  [{{< fa brands r-project size=2xl >}}](/analise_dados/clientes.html "Análise de dados"){aria-label="Análise de dados"}  |  |  [{{< fa list-check size=2xl >}}](/projeto/aa/aa.html "Projeto: Análise de Agrupamento"){aria-label="Projeto: Análise de Agrupamento"} -->
<!-- |  | Qui, 05/02 |  Análise Discriminante |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/analise_discr/discriminante.html#/title-slide "Análise Discriminante"){aria-label="Análise Discriminante"} |  |  |  |  |  | -->
<!-- | [15](programacao/semana-15.html) | Ter, 10/02 |   Análise Discriminante |  | [{{< fa file-powerpoint size=2xl >}}](/aulas/analise_discr/discriminante.html#/classificação-em-duas-população-normais-3 "Análise Discriminante"){aria-label="Análise Discriminante"} |  |  |  |  |  | -->
<!-- |  | Qui, 12/02 |   Não haverá aula! |  |  |  |  |  |  |  | -->
<!-- | [16](programacao/semana-16.html) | Ter, 17/02 | **Carnaval!** |  |  |  |  |  |  |  | -->
<!-- | | Qui, 19/02 | Análise Discriminante |  |  |  | |  [{{< fa brands r-project size=2xl >}}](/analise_dados/seguradora.html "Análise de dados"){aria-label="Análise de dados"}  |  |  [{{< fa list-check size=2xl >}}](/projeto/ad/ad.html "Projeto: Análise Discriminante"){aria-label="Projeto: Análise Discriminante"} -->
:::

```{r echo = FALSE}
knitr::knit_exit()
```
