---
title: "Lista de exercícios 02: Introdução à Estatística Multivariada"
format:
  html:
    number-sections: true
    toc: true
    toc-depth: 2
  pdf:
    number-sections: true
    toc: false
    toc-depth: 2
---

<p align="center" style="font-size: 40px"> 
`Data de entrega: 21 de setembro de 2026`
</p>


---

1)  Se $z_i = ay_i$, para $i = 1 \cdots n$, mostre que ${\overline{z}} =  a {\overline{y}}$.

---

2)  Se $z_i = ay_i$, para $i = 1 \cdots n$, mostre que $s^2_z = a^2s^2$.

---

3) A tabela abaixo fornece os dados de três variáveis (g/kg) medidas em 10 locais diferentes no Estado de Minas Gerais. As variáveis são:

$$
\begin{aligned}
X_1 &= \text{cálcio disponível no solo;} \\
X_2 &= \text{potássio disponível no solo;} \\
X_3 &= \text{fósforo disponível no solo.}
\end{aligned}
$$


| Locais | $X_1$ | $X_2$ | $X_3$ |
|:------:|--------:|--------:|--------:|
| 1  | 35 | 12 | 2.4 |
| 2  | 35 | 13 | 2.1 |
| 3  | 40 | 14 | 1.9 |
| 4  | 25 | 11 | 1.8 |
| 5  | 26 | 15 | 2.3 |
| 6  | 32 | 11 | 2.5 |
| 7  | 21 | 10 | 3.0 |
| 8  | 30 |  5 | 1.0 |
| 9  | 33 | 15 | 1.1 |
| 10 | 27 | 16 | 2.6 |



a) Encontre o vetor de médias amostrais $\mathbf{\overline{x}}$.
b) Calcule a matriz de covariâncias amostrais $\boldsymbol{S}$.
c) Obtenha a matriz de correlações amostrais $\boldsymbol{R}$.

---

4) Usando os dados apresentados na Tabela acima, calcule:

a) A variância generalizada amostral.
b) A variância total amostral.


---

5) Usando os dados apresentados na Tabela do exercício 3, defina $Z = 3X_1 - X_2 + 2X_3$ e calcule $\overline{z}$ e $s^2_Z$

---

6) Usando os dados apresentados na Tabela do exercício 3, defina $W = -2X_1 + 3X_2 + X_3$ e calcule:

a) $\overline{w}$ e $s^2_W$.
b) $\overline{\mathbf{y}}$ e $\boldsymbol{S}_y$ se $\boldsymbol{y} = \left[\begin{array}{cc} Z & W \end{array} \right]$.
c) Encontre a matriz $\boldsymbol{R}_{y}$.

---

7) Ainda utilizando os dados da Tabela do exercício 3, defina as seguintes combinações lineares das variáveis:



$$
\begin{aligned}
Z_1 &= X_1 + X_2 + X_3 \\
Z_2 &= 2X_1 - 3X_2 + 2X_3 \\
Z_3 &= -X_1 - 2X_2 - 3X_3
\end{aligned}
$$

a) Encontre $\overline{\mathbf{z}}$ e $\boldsymbol{S_z}$.
b) Através de $\boldsymbol{S_z}$, encontre $\boldsymbol{R_z}$.


---


8) Considere as amostras com 8 observações e 3 variáveis apresentadas a seguir:

|      |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |
|:----:|---:|---:|---:|---:|---:|---:|---:|---:|
| $X_1$ |  3 |  5 |  6 |  4 |  8 |  9 |  6 |  7 |
| $X_2$ |  6 | 11 | 11 |  9 | 15 | 16 | 10 | 12 |
| $X_3$ | 14 |  9 |  9 | 13 |  2 |  2 |  9 |  5 |



a) Calcule $\overline{\mathbf{x}}, \boldsymbol{S}, \boldsymbol{R}$.
b) Calcule as distâncias euclidiana, euclidiana padronizada e Mahalanobis de um ponto $P = (X_1, X_2, X_3) = (5, 12, 8)$ em relação ao a $\overline{\mathbf{x}}$.


---

9) Sejam dois vetores aleatórios ${\mathbf{x}} = [2 \hspace{0.2cm} 3]^t$ e  ${\mathbf{y}} = [2 \hspace{0.2cm} 1]^t$ e considere a matriz de covariâncias amostral igual a $\boldsymbol{S} = \left[ \begin{array}{ll} 10 & 6 \\6 & 8 \end{array} \right]$. Determine:


a) A distância euclidiana entre os dois vetores.
b) A distância generalizada de Karl Pearson.
c) A distância generalizada de Mahalanobis.

---

10) Obtenha as variâncias generalizada e total da matriz de covariâncias amostral apresentada a seguir. Determine a matriz de correlações e as variâncias generalizada e total correspondentes. 

$$\boldsymbol{S} = \left[ \begin{array}{ll} 32 & 12 \\ 12 & 10 \end{array} \right]$$
